//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptionsPlay.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OptionsPlay.Resources.DisplayNames", typeof(DisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Details.
        /// </summary>
        public static string BuyDetails {
            get {
                return ResourceManager.GetString("BuyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy or Sell.
        /// </summary>
        public static string BuyOrSell {
            get {
                return ResourceManager.GetString("BuyOrSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Strategy.
        /// </summary>
        public static string CallStrategy {
            get {
                return ResourceManager.GetString("CallStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Customize Expiry.
        /// </summary>
        public static string CanCustomizeExpiry {
            get {
                return ResourceManager.GetString("CanCustomizeExpiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Customize Width.
        /// </summary>
        public static string CanCustomizeWidth {
            get {
                return ResourceManager.GetString("CanCustomizeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Customize Wingspan.
        /// </summary>
        public static string CanCustomizeWingspan {
            get {
                return ResourceManager.GetString("CanCustomizeWingspan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Image.
        /// </summary>
        public static string CurrentImage {
            get {
                return ResourceManager.GetString("CurrentImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string DisplayOrder {
            get {
                return ResourceManager.GetString("DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leg Type.
        /// </summary>
        public static string LegType {
            get {
                return ResourceManager.GetString("LegType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occ Level.
        /// </summary>
        public static string OccLevel {
            get {
                return ResourceManager.GetString("OccLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pair Strategy.
        /// </summary>
        public static string PairStrategy {
            get {
                return ResourceManager.GetString("PairStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put Strategy.
        /// </summary>
        public static string PutStrategy {
            get {
                return ResourceManager.GetString("PutStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Details.
        /// </summary>
        public static string SellDetails {
            get {
                return ResourceManager.GetString("SellDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentiment.
        /// </summary>
        public static string Sentiment {
            get {
                return ResourceManager.GetString("Sentiment", resourceCulture);
            }
        }
    }
}
