//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptionsPlay.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumsLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumsLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OptionsPlay.Resources.EnumsLocalization", typeof(EnumsLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banking.
        /// </summary>
        public static string AccountType_BankingAccount {
            get {
                return ResourceManager.GetString("AccountType_BankingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string AccountType_CreditAccount {
            get {
                return ResourceManager.GetString("AccountType_CreditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment.
        /// </summary>
        public static string AccountType_InvestmentAccount {
            get {
                return ResourceManager.GetString("AccountType_InvestmentAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan.
        /// </summary>
        public static string AccountType_LoanAccount {
            get {
                return ResourceManager.GetString("AccountType_LoanAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing.
        /// </summary>
        public static string SchedulerExecutionStatus_Executing {
            get {
                return ResourceManager.GetString("SchedulerExecutionStatus_Executing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string SchedulerExecutionStatus_Failed {
            get {
                return ResourceManager.GetString("SchedulerExecutionStatus_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InQueue.
        /// </summary>
        public static string SchedulerExecutionStatus_InQueue {
            get {
                return ResourceManager.GetString("SchedulerExecutionStatus_InQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string SchedulerExecutionStatus_Pending {
            get {
                return ResourceManager.GetString("SchedulerExecutionStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SchedulerExecutionStatus_Success {
            get {
                return ResourceManager.GetString("SchedulerExecutionStatus_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminated.
        /// </summary>
        public static string SchedulerExecutionStatus_Terminated {
            get {
                return ResourceManager.GetString("SchedulerExecutionStatus_Terminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearish Turning Neutral.
        /// </summary>
        public static string SecondaryTag_BearishTurningNeutral {
            get {
                return ResourceManager.GetString("SecondaryTag_BearishTurningNeutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullish Turning Neutral.
        /// </summary>
        public static string SecondaryTag_BullishTurningNeutral {
            get {
                return ResourceManager.GetString("SecondaryTag_BullishTurningNeutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuation.
        /// </summary>
        public static string SecondaryTag_Continuation {
            get {
                return ResourceManager.GetString("SecondaryTag_Continuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overextended.
        /// </summary>
        public static string SecondaryTag_Overextended {
            get {
                return ResourceManager.GetString("SecondaryTag_Overextended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string SecondaryTag_Start {
            get {
                return ResourceManager.GetString("SecondaryTag_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearish.
        /// </summary>
        public static string Sentiment_Bearish {
            get {
                return ResourceManager.GetString("Sentiment_Bearish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullish.
        /// </summary>
        public static string Sentiment_Bullish {
            get {
                return ResourceManager.GetString("Sentiment_Bullish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        public static string Sentiment_Neutral {
            get {
                return ResourceManager.GetString("Sentiment_Neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharpMove.
        /// </summary>
        public static string Sentiment_SharpMove {
            get {
                return ResourceManager.GetString("Sentiment_SharpMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearish.
        /// </summary>
        public static string SignalInterpretation_Bearish {
            get {
                return ResourceManager.GetString("SignalInterpretation_Bearish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearish, but Turning Bullish.
        /// </summary>
        public static string SignalInterpretation_BearishTurningBullish {
            get {
                return ResourceManager.GetString("SignalInterpretation_BearishTurningBullish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullish.
        /// </summary>
        public static string SignalInterpretation_Bullish {
            get {
                return ResourceManager.GetString("SignalInterpretation_Bullish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullish, but Trending Bearish.
        /// </summary>
        public static string SignalInterpretation_BullishTrendingBearish {
            get {
                return ResourceManager.GetString("SignalInterpretation_BullishTrendingBearish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullish, but Turning Bearish.
        /// </summary>
        public static string SignalInterpretation_BullishTurningBearish {
            get {
                return ResourceManager.GetString("SignalInterpretation_BullishTurningBearish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extremely Bearish.
        /// </summary>
        public static string SignalInterpretation_ExtremelyBearish {
            get {
                return ResourceManager.GetString("SignalInterpretation_ExtremelyBearish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extremely Bullish.
        /// </summary>
        public static string SignalInterpretation_ExtremelyBullish {
            get {
                return ResourceManager.GetString("SignalInterpretation_ExtremelyBullish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mildly Bearish.
        /// </summary>
        public static string SignalInterpretation_MildlyBearish {
            get {
                return ResourceManager.GetString("SignalInterpretation_MildlyBearish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mildly Bullish.
        /// </summary>
        public static string SignalInterpretation_MildlyBullish {
            get {
                return ResourceManager.GetString("SignalInterpretation_MildlyBullish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        public static string SignalInterpretation_Neutral {
            get {
                return ResourceManager.GetString("SignalInterpretation_Neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        public static string SignalInterpretation_Nothing {
            get {
                return ResourceManager.GetString("SignalInterpretation_Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overbought.
        /// </summary>
        public static string SignalInterpretation_Overbought {
            get {
                return ResourceManager.GetString("SignalInterpretation_Overbought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overbought Unsusta.
        /// </summary>
        public static string SignalInterpretation_OverboughtUnsustainable {
            get {
                return ResourceManager.GetString("SignalInterpretation_OverboughtUnsustainable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oversold.
        /// </summary>
        public static string SignalInterpretation_Oversold {
            get {
                return ResourceManager.GetString("SignalInterpretation_Oversold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oversold Unsustainable.
        /// </summary>
        public static string SignalInterpretation_OversoldUnsustainable {
            get {
                return ResourceManager.GetString("SignalInterpretation_OversoldUnsustainable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong Trend Bearish.
        /// </summary>
        public static string SignalInterpretation_StrongTrendBearish {
            get {
                return ResourceManager.GetString("SignalInterpretation_StrongTrendBearish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong Trend Bullish.
        /// </summary>
        public static string SignalInterpretation_StrongTrendBullish {
            get {
                return ResourceManager.GetString("SignalInterpretation_StrongTrendBullish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trending Bearish.
        /// </summary>
        public static string SignalInterpretation_TrendingBearish {
            get {
                return ResourceManager.GetString("SignalInterpretation_TrendingBearish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trending Bullish.
        /// </summary>
        public static string SignalInterpretation_TrendingBullish {
            get {
                return ResourceManager.GetString("SignalInterpretation_TrendingBullish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning Bearish.
        /// </summary>
        public static string SignalInterpretation_TurningBearish {
            get {
                return ResourceManager.GetString("SignalInterpretation_TurningBearish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCI Dip In Bullish Trend.
        /// </summary>
        public static string TradeIdeaRule_CciDipInBullishTrend {
            get {
                return ResourceManager.GetString("TradeIdeaRule_CciDipInBullishTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCI Overbought Bearish Crossover.
        /// </summary>
        public static string TradeIdeaRule_CciOverboughtBearishCrossover {
            get {
                return ResourceManager.GetString("TradeIdeaRule_CciOverboughtBearishCrossover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCI Oversold Bullish Crossover.
        /// </summary>
        public static string TradeIdeaRule_CciOversoldBullishCrossover {
            get {
                return ResourceManager.GetString("TradeIdeaRule_CciOversoldBullishCrossover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCI Rally in Bearish Trend.
        /// </summary>
        public static string TradeIdeaRule_CciRallyInBearishTrend {
            get {
                return ResourceManager.GetString("TradeIdeaRule_CciRallyInBearishTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFI Overbought Bearish Crossover.
        /// </summary>
        public static string TradeIdeaRule_MfiOverboughtBearishCrossover {
            get {
                return ResourceManager.GetString("TradeIdeaRule_MfiOverboughtBearishCrossover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFI Oversold Bullish Crossover.
        /// </summary>
        public static string TradeIdeaRule_MfiOversoldBullishCrossover {
            get {
                return ResourceManager.GetString("TradeIdeaRule_MfiOversoldBullishCrossover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSI Dip in Bullish Trend.
        /// </summary>
        public static string TradeIdeaRule_RsiDipInBullishTrend {
            get {
                return ResourceManager.GetString("TradeIdeaRule_RsiDipInBullishTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSI Overbought Bearish Crossover.
        /// </summary>
        public static string TradeIdeaRule_RsiOverboughtBearishCrossover {
            get {
                return ResourceManager.GetString("TradeIdeaRule_RsiOverboughtBearishCrossover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSI Oversold Bullish Crossover.
        /// </summary>
        public static string TradeIdeaRule_RsiOversoldBullishCrossover {
            get {
                return ResourceManager.GetString("TradeIdeaRule_RsiOversoldBullishCrossover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSI Rally in Bearish Trend.
        /// </summary>
        public static string TradeIdeaRule_RsiRallyInBearishTrend {
            get {
                return ResourceManager.GetString("TradeIdeaRule_RsiRallyInBearishTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stochastic Overbought Bearish Crossover.
        /// </summary>
        public static string TradeIdeaRule_StochasticOverboughtBearishCrossover {
            get {
                return ResourceManager.GetString("TradeIdeaRule_StochasticOverboughtBearishCrossover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stochastic Oversold Bullish Crossover.
        /// </summary>
        public static string TradeIdeaRule_StochasticOversoldBullishCrossover {
            get {
                return ResourceManager.GetString("TradeIdeaRule_StochasticOversoldBullishCrossover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Williams %R Overbought Bearish Crossover.
        /// </summary>
        public static string TradeIdeaRule_WilliamsOverboughtBearishCrossover {
            get {
                return ResourceManager.GetString("TradeIdeaRule_WilliamsOverboughtBearishCrossover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Williams %R Oversold Bullish Crossover.
        /// </summary>
        public static string TradeIdeaRule_WilliamsROversoldBullishCrossover {
            get {
                return ResourceManager.GetString("TradeIdeaRule_WilliamsROversoldBullishCrossover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is currently in a bullish trend and recently experienced a short-term price pullback providing a good buying opportunity..
        /// </summary>
        public static string TradeIdeaRuleSentence_CciDipInBullishTrend {
            get {
                return ResourceManager.GetString("TradeIdeaRuleSentence_CciDipInBullishTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is currently overbought, and momentum is showing signs of a trend reversal, providing a good selling opportunity..
        /// </summary>
        public static string TradeIdeaRuleSentence_CciOverboughtBearishCrossover {
            get {
                return ResourceManager.GetString("TradeIdeaRuleSentence_CciOverboughtBearishCrossover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is currently oversold, and momentum is showing signs of a trend reversal, providing a good buying opportunity..
        /// </summary>
        public static string TradeIdeaRuleSentence_CciOversoldBullishCrossover {
            get {
                return ResourceManager.GetString("TradeIdeaRuleSentence_CciOversoldBullishCrossover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is currently in a bearish trend and recently experienced a short-term price rally providing a good selling opportunity..
        /// </summary>
        public static string TradeIdeaRuleSentence_CciRallyInBearishTrend {
            get {
                return ResourceManager.GetString("TradeIdeaRuleSentence_CciRallyInBearishTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is currently overbought, and momentum is showing signs of a trend reversal, providing a good selling opportunity..
        /// </summary>
        public static string TradeIdeaRuleSentence_MfiOverboughtBearishCrossover {
            get {
                return ResourceManager.GetString("TradeIdeaRuleSentence_MfiOverboughtBearishCrossover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is currently oversold, and momentum is showing signs of a trend reversal, providing a good buying opportunity..
        /// </summary>
        public static string TradeIdeaRuleSentence_MfiOversoldBullishCrossover {
            get {
                return ResourceManager.GetString("TradeIdeaRuleSentence_MfiOversoldBullishCrossover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is currently in a bullish trend and recently experienced a short-term price pullback providing a good buying opportunity..
        /// </summary>
        public static string TradeIdeaRuleSentence_RsiDipInBullishTrend {
            get {
                return ResourceManager.GetString("TradeIdeaRuleSentence_RsiDipInBullishTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is currently overbought, and momentum is showing signs of a trend reversal, providing a good selling opportunity..
        /// </summary>
        public static string TradeIdeaRuleSentence_RsiOverboughtBearishCrossover {
            get {
                return ResourceManager.GetString("TradeIdeaRuleSentence_RsiOverboughtBearishCrossover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is currently oversold, and momentum is showing signs of a trend reversal, providing a good buying opportunity..
        /// </summary>
        public static string TradeIdeaRuleSentence_RsiOversoldBullishCrossover {
            get {
                return ResourceManager.GetString("TradeIdeaRuleSentence_RsiOversoldBullishCrossover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is currently in a bearish trend and recently experienced a short-term price rally providing a good selling opportunity..
        /// </summary>
        public static string TradeIdeaRuleSentence_RsiRallyInBearishTrend {
            get {
                return ResourceManager.GetString("TradeIdeaRuleSentence_RsiRallyInBearishTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is currently overbought, and momentum is showing signs of a trend reversal, providing a good selling opportunity..
        /// </summary>
        public static string TradeIdeaRuleSentence_StochasticOverboughtBearishCrossover {
            get {
                return ResourceManager.GetString("TradeIdeaRuleSentence_StochasticOverboughtBearishCrossover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is currently oversold, and momentum is showing signs of a trend reversal, providing a good buying opportunity..
        /// </summary>
        public static string TradeIdeaRuleSentence_StochasticOversoldBullishCrossover {
            get {
                return ResourceManager.GetString("TradeIdeaRuleSentence_StochasticOversoldBullishCrossover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is currently overbought, and momentum is showing signs of a trend reversal, providing a good selling opportunity..
        /// </summary>
        public static string TradeIdeaRuleSentence_WilliamsOverboughtBearishCrossover {
            get {
                return ResourceManager.GetString("TradeIdeaRuleSentence_WilliamsOverboughtBearishCrossover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is currently oversold, and momentum is showing signs of a trend reversal, providing a good buying opportunity..
        /// </summary>
        public static string TradeIdeaRuleSentence_WilliamsROversoldBullishCrossover {
            get {
                return ResourceManager.GetString("TradeIdeaRuleSentence_WilliamsROversoldBullishCrossover", resourceCulture);
            }
        }
    }
}
