//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptionsPlay.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OptionsPlay.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during saving changes to DB.
        /// </summary>
        public static string DbCommitError {
            get {
                return ResourceManager.GetString("DbCommitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double enum declaration. Name should be unique among all enums of the same type.
        /// </summary>
        public static string DoubleEnumDeclaration {
            get {
                return ResourceManager.GetString("DoubleEnumDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max size of {0} is {1} mb.
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse value {0} as date. Date must be of format {1}..
        /// </summary>
        public static string InvalidDateDormat {
            get {
                return ResourceManager.GetString("InvalidDateDormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot query the data between {0} and {1}.
        /// </summary>
        public static string InvalidDateRange {
            get {
                return ResourceManager.GetString("InvalidDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot map value {0} to enum {1} .
        /// </summary>
        public static string InvalidEnumValue {
            get {
                return ResourceManager.GetString("InvalidEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator type &apos;{0}&apos; cannot be found.
        /// </summary>
        public static string InvalidIndicator {
            get {
                return ResourceManager.GetString("InvalidIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions collection cannot contain &apos;NotAuthenticatedAccessOnly&apos; together with any other permissions.
        /// </summary>
        public static string InvalidPermissionsScope {
            get {
                return ResourceManager.GetString("InvalidPermissionsScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;T&apos; must be an enum type..
        /// </summary>
        public static string NotEnumType {
            get {
                return ResourceManager.GetString("NotEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be not equal to {1}.
        /// </summary>
        public static string NotEqualTo {
            get {
                return ResourceManager.GetString("NotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already used in another strategy group.
        /// </summary>
        public static string OnlyOneGroupedStrategy {
            get {
                return ResourceManager.GetString("OnlyOneGroupedStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one leg of &apos;Security&apos; type is allowed.
        /// </summary>
        public static string OnlyOneSecurityLeg {
            get {
                return ResourceManager.GetString("OnlyOneSecurityLeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} and {2}.
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection &apos;{0}&apos; must contain at least one item.
        /// </summary>
        public static string RequiredCollection {
            get {
                return ResourceManager.GetString("RequiredCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer code and Account code cannot be empty at the same time..
        /// </summary>
        public static string SZKingdom_CustAndAccCodeNull {
            get {
                return ResourceManager.GetString("SZKingdom_CustAndAccCodeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer code cannot be empty..
        /// </summary>
        public static string SZKingdom_CustomerCodeEmpty {
            get {
                return ResourceManager.GetString("SZKingdom_CustomerCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SZKingdom field {0} has already been defined. Duplicate at property &apos;{1}&apos;.
        /// </summary>
        public static string SZKingdom_DublicateProperty {
            get {
                return ResourceManager.GetString("SZKingdom_DublicateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer code and account code cannot be empty at the same time..
        /// </summary>
        public static string SZKingdom_EmptyAccountIds {
            get {
                return ResourceManager.GetString("SZKingdom_EmptyAccountIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account ID {0} is invalid..
        /// </summary>
        public static string SZKingdom_Invalid_Account {
            get {
                return ResourceManager.GetString("SZKingdom_Invalid_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No query results for request &apos;{0}&apos; with parameters &apos;{1}&apos;.
        /// </summary>
        public static string SZKingdom_NoResults {
            get {
                return ResourceManager.GetString("SZKingdom_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option number cannot be empty when the order is an option order.
        /// </summary>
        public static string SZKingdom_OptionNumberCanNotBeEmpty {
            get {
                return ResourceManager.GetString("SZKingdom_OptionNumberCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order price cannot be empty when the oder is open/close option position.
        /// </summary>
        public static string SZKingdom_OrderPriceCanNotBeEmpty {
            get {
                return ResourceManager.GetString("SZKingdom_OrderPriceCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single result is expected  for request &apos;{0}&apos; with parameters &apos;{1}&apos;.
        /// </summary>
        public static string SZKingdom_SingleResultExpected {
            get {
                return ResourceManager.GetString("SZKingdom_SingleResultExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock code cannot be empty when the order is a stock order.
        /// </summary>
        public static string SZKingdom_StockCanNotBeEmpty {
            get {
                return ResourceManager.GetString("SZKingdom_StockCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade account cannot be empty..
        /// </summary>
        public static string SZKingdom_TradeAccountCanNotBeEmpty {
            get {
                return ResourceManager.GetString("SZKingdom_TradeAccountCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid extensions for {0}: {1}.
        /// </summary>
        public static string ValidFileExtensions {
            get {
                return ResourceManager.GetString("ValidFileExtensions", resourceCulture);
            }
        }
    }
}
